git:
  depth: 99999

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    update: true
  chrome: stable
  sonarcloud:
    organization: codeborne
    token:
      - secure: "lhf27njZE3PpaoLdl0+hrjFaqe7VsPm39rfbmQhq0u1fLO/6BLbHxWUwo1GleI+Hxh1DAyoNRpR+uZOwqx3hOqRotTnLbaInvGmXZasRUq/DRMzN0WMGmarqmDpHAsJ7TZL6ECo4skoKRapziSdjxkc8eyQ45ZgNezTFpFfQJDM="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr /home/travis/.m2/repository/webdriver/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - ./gradlew check --no-daemon --console=plain
  - ./gradlew htmlunit --no-daemon --console=plain
  - ./gradlew chrome --no-daemon --console=plain --stacktrace
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew sonarqube --no-daemon --console=plain -Dsonar.host.url=${SONAR_HOST} -Dsonar.branch.name=${TRAVIS_BRANCH}; fi'

after_script: "./.upload_reports.sh"

notifications:
  slack:
    rooms:
      secure: "a+W3yrcab0GVRhmIUXsdV1KpNxX6Qe7LnX6vq4Ou4mCSSaBln0mL0y4Gs1GSPdiq5PWhYrcIgAsESQiCDbi5JoW//GyEovZvY+WDgnhrskoOLFgWqxhT1yInDkLRfkQZAdL/5uWOBDSr1d+2/1qqeciWMebQQZoEezeKoKwPtdQ="
