branches:
  only:
    - master

notifications:
  slack: 
    rooms:
      secure: "a+W3yrcab0GVRhmIUXsdV1KpNxX6Qe7LnX6vq4Ou4mCSSaBln0mL0y4Gs1GSPdiq5PWhYrcIgAsESQiCDbi5JoW//GyEovZvY+WDgnhrskoOLFgWqxhT1yInDkLRfkQZAdL/5uWOBDSr1d+2/1qqeciWMebQQZoEezeKoKwPtdQ="
  
language: java
sudo: false
cache:
  directories:
  - $HOME/.gradle

script: "gradle clean test firefox testng"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - openjdk7

addons:
  firefox: "47.0.1"