version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/gradle"
    update_schedule: "daily"
