name: 'Run tests'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '17'
      - name: Setup Edge
        if: ${{ contains(matrix.gradle-task, 'edge') }}
        uses: browser-actions/setup-edge@latest
      - name: Set-DisplayResolution
        shell: pwsh
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-win-${{matrix.gradle-task}}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results

  run-tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '17'
      - name: Setup Firefox
        if: ${{ matrix.gradle-task != 'check' }}
        uses: browser-actions/setup-firefox@latest
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle-task }} --no-parallel --no-daemon --console=plain
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-linux-${{matrix.gradle-task}}
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
