name: Run tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Check
        run: ./gradlew clean check --no-daemon --console=plain --info --rerun-tasks
      - name: Grid tests
        run: ./gradlew grid --no-daemon --console=plain --info --rerun-tasks
      - name: Chrome tests
        run: ./gradlew chrome_headless --tests 'integration.**.*Frame*Test*' --info --rerun-tasks
      - name: Firefox tests
        run: ./gradlew firefox_headless --tests 'integration.**.*Frame*Test*' --info --rerun-tasks
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: build/reports/
