name: 'Run tests'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ios-tests:
    runs-on: macOS-14
    env:
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 127.0.0.1
      APPIUM_STARTUP_TIMEOUT_SEC: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup iOS simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'
          os: 'iOS'
          os_version: '17.5'
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Appium
        run: |
          npm install -g appium
          npm install -g appium-doctor
      - name: Log Xcode Version
        run: xcodebuild -version
      - name: Log Installed Simulators
        run: xcrun simctl list
      - name: Log Runtimes
        run: xcrun simctl list runtimes
      - name: Start Appium server
        run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install xcuitest
          appium driver run xcuitest build-wda
          appium driver install safari
          appium-doctor
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '17'
      - name: Run iOS tests
        run: ./gradlew ios --no-daemon --console=plain -i
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-ios
          path: |
            **/build/reports
            **/build/test-results
            **/appium.log
