name: Run tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-main-tests-{0}', github.sha) || format('ci-main-tests-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  run-tests-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check', 'edge_headless' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Edge
        if: ${{ matrix.gradle-task == 'edge_headless' }}
        uses: browser-actions/setup-edge@latest
      - name: Build with Gradle
        run: ./gradlew ${{ matrix.gradle-task }} --no-daemon --console=plain -i
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report-win
          path: ./**/build/reports
  run-tests-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle-task: [ 'check', 'firefox_headless', 'chrome_headless' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Firefox
        if: ${{ matrix.gradle-task != 'check' }}
        run: |
          sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa
          sudo apt-get update
          sudo apt-get install firefox-trunk
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew ${{ matrix.gradle-task }} --no-daemon --console=plain -i
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: ./**/build/reports/
