name: 'Run tests'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '17'
      - name: Start selenoid
        uses: BorisOsipov/selenoid-github-action@1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run the tests
        run: ./gradlew selenoidTests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-selenoid
          retention-days: 14
          path: |
            **/build/reports
            **/build/test-results
